<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require_once(APPPATH.'controllers/Secure_area.php');

class Laporan extends Secure_area {
	public function __construct() {
			parent::__construct();			
            $this->load->model('kepegawaian/M_datatable','',TRUE);	
            $this->load->helper(array('html','url')); 
            $this->load->model('kepegawaian/M_pegawai','',TRUE);
            $this->load->model('irj/rjmpencarian','',TRUE);
            $this->load->helper('pdf_helper');		
	}

    // public function index()
    // {
    //     if ($id == '') {
    //         $data['title'] = 'Data Personil';
    //         $this->load->view('kepegawaian/data_personil',$data);
    //     } else {                    
    //         $data['title'] = 'Data Personil';
    //         $data['jenis'] = $this->M_pegawai->get_select_jenis();
    //         $data['pangkat'] = $this->rjmpencarian->get_pangkat()->result();
    //         $data['data_pegawai'] = $this->M_pegawai->show_personil($id);
    //         $this->load->view("kepegawaian/personil", $data);
    //     }
    // }

    public function daftar_nominatif()
    {        
            $data['title'] = 'Daftar Nominatif Rumkital Dr. Mintohardjo';
            $this->load->view('kepegawaian/laporan/daftar_nominatif',$data);       
    }  

    function download_kekuatan_prajurit_pns()
    {   
        $data_kekuatan=$this->M_pegawai->download_kekuatan_prajurit_pns()->result_array(); 
        // print_r($data_kekuatan);die();              
        // if (count($data_personil) == 0) {
        //     $message =  'empty';
        //     $this->session->set_flashdata('notification', $message);
        //     redirect('kepegawaian/laporan/daftar_nominatif');
        // }
        // print_r(json_encode($data_personil));die();
        $objPHPExcel = new PHPExcel();       
        $namars=$this->config->item('namars');
        $objPHPExcel = PHPExcel_IOFactory::load(APPPATH.'third_party/kepegawaian/kekuatan_prajurit_pns.xlsx');
        $objPHPExcel->getProperties()->setCreator($namars)  
                ->setLastModifiedBy($namars)  
                ->setTitle("LAPORAN KEKUATAN DATA PRAJURIT & PNS ".$namars."")  
                ->setSubject("LAPORAN KEKUATAN DATA PRAJURIT & PNS ".$namars." Document")  
                ->setDescription("LAPORAN KEKUATAN DATA PRAJURIT & PNS ".$namars.", generated by HMIS.")  
                ->setKeywords($namars)  
                ->setCategory("LAPORAN KEKUATAN DATA PRAJURIT & PNS ".$namars.""); 

        $objPHPExcel->setActiveSheetIndex(0);               

        $rowPrajurit = 13;
        $rowPns = 17;
        // $subrow = 13;        
        $pati='-';
        for ($i=0; $i <= 7; $i++) {                
            $pati+=$data_kekuatan[$i]['total'];
        }
        if ($pati == 0) {
            $pati='-';
        }    
        // $column = 'D'; 
        // $columnPns = 'D'; 
        // for ($i=0; $i < count($data_kekuatan); $i++) {     
        //     if ($data_kekuatan[$i]['jenis'] == 'TNI') {                        
        //         $objPHPExcel->getActiveSheet()->setCellValue($column.$headerPrajurit, $data_kekuatan[$i]['pangkat']);
        //         $objPHPExcel->getActiveSheet()->setCellValue($column.$rowPrajurit, $data_kekuatan[$i]['total']);                
        //     }
        //     if ($data_kekuatan[$i]['jenis'] == 'PNS') {                  
        //         $header_pns = explode(' ', $data_kekuatan[$i]['pangkat']);
        //         $objPHPExcel->getActiveSheet()->setCellValue($columnPns.$headerPns, array_pop($header_pns));
        //         $objPHPExcel->getActiveSheet()->setCellValue($columnPns.$rowPns, $data_kekuatan[$i]['total']);   
        //         $objPHPExcel->getActiveSheet()->getColumnDimension($columnPns)->setAutoSize(true);
        //         ++$columnPns;             
        //     }
        //     ++$column;                          
        // } 
        // foreach($data_kekuatan as $row) {    
            $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowPrajurit, $pati);
            $objPHPExcel->getActiveSheet()->setCellValue('E'.$rowPrajurit, $data_kekuatan[8]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowPrajurit, $data_kekuatan[9]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowPrajurit, $data_kekuatan[10]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowPrajurit, $data_kekuatan[11]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowPrajurit, $data_kekuatan[12]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowPrajurit, $data_kekuatan[13]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('K'.$rowPrajurit, $data_kekuatan[14]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('L'.$rowPrajurit, $data_kekuatan[15]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('M'.$rowPrajurit, $data_kekuatan[16]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('N'.$rowPrajurit, $data_kekuatan[17]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('O'.$rowPrajurit, $data_kekuatan[18]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('P'.$rowPrajurit, $data_kekuatan[19]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('Q'.$rowPrajurit, $data_kekuatan[20]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('R'.$rowPrajurit, $data_kekuatan[21]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('S'.$rowPrajurit, $data_kekuatan[22]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('T'.$rowPrajurit, $data_kekuatan[23]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('U'.$rowPrajurit, $data_kekuatan[24]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('V'.$rowPrajurit, $data_kekuatan[25]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('W'.$rowPrajurit, $data_kekuatan[26]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('X'.$rowPrajurit, $data_kekuatan[27]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('Y'.$rowPrajurit, $data_kekuatan[28]['total']);

            $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowPns, $data_kekuatan[29]['total']);
            $objPHPExcel->getActiveSheet()->setCellValue('E'.$rowPns, $data_kekuatan[30]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowPns, $data_kekuatan[31]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowPns, $data_kekuatan[32]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowPns, $data_kekuatan[33]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowPns, $data_kekuatan[34]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowPns, $data_kekuatan[35]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('K'.$rowPns, $data_kekuatan[36]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('L'.$rowPns, $data_kekuatan[37]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('M'.$rowPns, $data_kekuatan[38]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('N'.$rowPns, $data_kekuatan[39]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('O'.$rowPns, $data_kekuatan[40]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('P'.$rowPns, $data_kekuatan[41]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('Q'.$rowPns, $data_kekuatan[42]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('R'.$rowPns, $data_kekuatan[43]['total']);
            $objPHPExcel->getActiveSheet()->SetCellValue('S'.$rowPns, $data_kekuatan[44]['total']);                           
        // }
                
        $filename = "LAPORAN KEKUATAN DATA PRAJURIT & PNS ".$namars."";
        ob_end_clean();
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: no-store, no-cache, must-revalidate");
        header("Cache-Control: post-check=0, pre-check=0", false);
        header("Pragma: no-cache");
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$filename.'.xls"');          
        $object_writer = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');                
        $object_writer->save('php://output');
    }

    function download_daftar_nominatif($jenis='')
    {   
        $data_personil=$this->M_pegawai->download_daftar_nominatif($jenis)->result();         
        // if (count($data_personil) == 0) {
        //     $message =  'empty';
        //     $this->session->set_flashdata('notification', $message);
        //     redirect('kepegawaian/laporan/daftar_nominatif');
        // }
        // print_r(json_encode($data_personil));die();
        $objPHPExcel = new PHPExcel();       
        $namars=$this->config->item('namars');
        $objPHPExcel = PHPExcel_IOFactory::load(APPPATH.'third_party/kepegawaian/daftar_nominatif_pns.xlsx');
        $objPHPExcel->getProperties()->setCreator($namars)  
                ->setLastModifiedBy($namars)  
                ->setTitle("DAFTAR NOMINATIF ".$jenis." ".$namars."")  
                ->setSubject("DAFTAR NOMINATIF ".$jenis." ".$namars." Document")  
                ->setDescription("DAFTAR NOMINATIF ".$jenis." ".$namars.", generated by HMIS.")  
                ->setKeywords($namars)  
                ->setCategory("DAFTAR NOMINATIF ".$jenis." ".$namars.""); 

        $objPHPExcel->setActiveSheetIndex(0);               

        $rowCount = 12;
        $subrow = 13;
        $i=1;
        foreach($data_personil as $row) {                
            $objPHPExcel->getActiveSheet()->mergeCells("B$rowCount:B$subrow")->getStyle("B$rowCount:B$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );
            $objPHPExcel->getActiveSheet()->getStyle("C$rowCount:C$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'outline' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("D$rowCount:D$subrow")->getStyle("D$rowCount:D$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("E$rowCount:E$subrow")->getStyle("E$rowCount:E$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("F$rowCount:F$subrow")->getStyle("F$rowCount:F$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("G$rowCount:G$subrow")->getStyle("G$rowCount:G$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("H$rowCount:H$subrow")->getStyle("H$rowCount:H$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("I$rowCount:I$subrow")->getStyle("I$rowCount:I$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("J$rowCount:J$subrow")->getStyle("J$rowCount:J$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("K$rowCount:K$subrow")->getStyle("K$rowCount:K$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("L$rowCount:L$subrow")->getStyle("L$rowCount:L$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("M$rowCount:M$subrow")->getStyle("M$rowCount:M$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("N$rowCount:N$subrow")->getStyle("N$rowCount:N$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );  
            $objPHPExcel->getActiveSheet()->mergeCells("O$rowCount:O$subrow")->getStyle("O$rowCount:O$subrow")->applyFromArray(
                array(
                    'borders' => array(
                        'allborders' => array(
                            'style' => PHPExcel_Style_Border::BORDER_THIN,
                            'color' => array('rgb' => '000000')
                        )
                    )
                )
            );             
                                 
            $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $i++);
            $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->nama);
            if ($row->tmpt_lahir == '') {
                $tmpt_lahir='-';
            } else $tmpt_lahir=$row->tmpt_lahir;
            if ($row->tgl_lahir == '') {
                $tgl_lahir='-';
            } else $tgl_lahir=$row->tgl_lahir;
            $objPHPExcel->getActiveSheet()->SetCellValue('C'.$subrow, ucfirst($tmpt_lahir).', '.$tgl_lahir);            
            $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $row->pangkat);
            $objPHPExcel->getActiveSheet()->setCellValueExplicit('E'.$rowCount, $row->nip_nrp,PHPExcel_Cell_DataType::TYPE_STRING);
            $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $row->tmt_masuk);
            $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, $row->tmt_pangkat); // pangkat terakhir
            $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, $row->jabatan);
            $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, $row->tmt_jabatan);
            $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, $row->pend_umum_akhir); // pend umum
            $objPHPExcel->getActiveSheet()->SetCellValue('K'.$rowCount, $row->pend_tni_akhir); // pend AL
            $objPHPExcel->getActiveSheet()->SetCellValue('L'.$rowCount, $row->k_tk);
            $objPHPExcel->getActiveSheet()->SetCellValue('M'.$rowCount, $row->agama);
            $objPHPExcel->getActiveSheet()->SetCellValue('N'.$rowCount, $row->status_rumah);
            $objPHPExcel->getActiveSheet()->SetCellValue('O'.$rowCount, $row->alamat);
            // $rowCount++;
            $rowCount=$subrow+1;
            $subrow=$rowCount+1;
        }
                
        $filename = "DAFTAR NOMINATIF ".$jenis." ".$namars."";
        ob_end_clean();
        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        header("Cache-Control: no-store, no-cache, must-revalidate");
        header("Cache-Control: post-check=0, pre-check=0", false);
        header("Pragma: no-cache");
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$filename.'.xls"');          
        $object_writer = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');                
        $object_writer->save('php://output');
        // return true;
    }

    // public function download_daftar_nominatif($jenis='PNS'){
    //     // require_once (APPPATH.'third_party/PHPExcel.php');
    //     // $this->load->library('Excel'); 
    //     $this->load->library("Excel/PHPExcel");
    //       $objPHPExcel = new PHPExcel();
 
    //         //set Sheet yang akan diolah 
    //         $objPHPExcel->setActiveSheetIndex(0)
    //                 //mengisikan value pada tiap-tiap cell, A1 itu alamat cellnya 
    //                 //Hello merupakan isinya
    //                                     ->setCellValue('A1', 'Hello')
    //                                     ->setCellValue('B2', 'Ini')
    //                                     ->setCellValue('C1', 'Excel')
    //                                     ->setCellValue('D2', 'Pertamaku');
    //         //set title pada sheet (me rename nama sheet)
    //         $objPHPExcel->getActiveSheet()->setTitle('Excel Pertama');
 
    //         //mulai menyimpan excel format xlsx, kalau ingin xls ganti Excel2007 menjadi Excel5          
    //         $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
 
    //         //sesuaikan headernya 
    //         header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
    //         header("Cache-Control: no-store, no-cache, must-revalidate");
    //         header("Cache-Control: post-check=0, pre-check=0", false);
    //         header("Pragma: no-cache");
    //         header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    //         //ubah nama file saat diunduh
    //         header('Content-Disposition: attachment;filename="hasilExcel.xls"');
    //         //unduh file
    //         ob_end_clean();
    //         $objWriter->save("php://output");
    //         die();
    //     require_once (APPPATH.'third_party/PHPExcel.php');
    //     $this->load->library('Excel');  
           
    //     // Create new PHPExcel object  
    //     $objPHPExcel = new PHPExcel();   
    //     $namars=$this->config->item('namars');
    //     // Set document properties  
    //     $objPHPExcel->getProperties()->setCreator($namars)  
    //             ->setLastModifiedBy($namars)  
    //             ->setTitle("Laporan Diagnosa ".$namars."")  
    //             ->setSubject("Laporan Diagnosa ".$namars." Document")  
    //             ->setDescription("Laporan Diagnosa ".$namars.", generated by HMIS.")  
    //             ->setKeywords($namars)  
    //             ->setCategory("Laporan Diagnosa");  

    //     //$objReader = PHPExcel_IOFactory::createReader('Excel2007');    
    //     //$objPHPExcel = $objReader->load("project.xlsx");
           
    //     $objReader= PHPExcel_IOFactory::createReader('Excel2007');
    //     // $objReader->setReadDataOnly(true);

    //     // $awal = $this->input->post('tanggal_awal');
    //     // $akhir = $this->input->post('tanggal_akhir');
                    
    //     $data_personil=$this->M_pegawai->download_daftar_nominatif($jenis)->result(); 
    //     // print_r($data_personil);die();
    
    //     $objPHPExcel=$objReader->load(APPPATH.'third_party/kepegawaian/daftar_nominatif_pns.xlsx');
    //     // Set active sheet index to the first sheet, so Excel opens this as the first sheet  
    //     // $objPHPExcel->setActiveSheetIndex(0);  
    //     // Add some data  

    //     //MERGE
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A1:B1');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A2:B2');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A4:U4');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A5:U5');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A6:U6');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('A8:A9');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('B8:B9');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('C8:C9');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('D8:F8');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('G8:M8');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('N8:N9');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('O8:U8');
    //     // $objPHPExcel->getActiveSheet()->mergeCells('V8:V9');
    //     // $objPHPExcel->getActiveSheet()->SetCellValue('A5', $nama_poli);
    //     // $objPHPExcel->getActiveSheet()->SetCellValue('A6', "Periode ".date('d F Y', strtotime($param1))." - ".date('d F Y', strtotime($param2)));

    //     // //BOLD
    //     // $objPHPExcel->getActiveSheet()->getStyle('A1')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A2')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A4')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A5')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A6')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('B8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('C8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('D8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('G8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('N8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('O8')->getFont()->setBold(true);
    //     // $objPHPExcel->getActiveSheet()->getStyle('V8')->getFont()->setBold(true);

    //     // //CENTER HORIZONTAL
    //     // $objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A6')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('B8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('C8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('D8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('G8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('N8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('O8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('V8')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

    //     // //CENTER VERTICAL
    //     // $objPHPExcel->getActiveSheet()->getStyle('A1')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A2')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A4')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A5')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A6')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('A8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('B8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('C8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('D8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('G8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('N8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('O8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
    //     // $objPHPExcel->getActiveSheet()->getStyle('V8')->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);

    //     // //AUTO SIZE
    //     // $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setAutoSize(true);
    //     // $objPHPExcel->getActiveSheet()->getColumnDimension('R')->setAutoSize(true);
    //     // $objPHPExcel->getActiveSheet()->getColumnDimension('T')->setAutoSize(true);
    //     // $objPHPExcel->getActiveSheet()->setAutoFilter('A3:O3');

    //     $rowCount = 12;
    //     $i=1;
    //     foreach($data_personil as $row){ 
    //         print_r($data_personil->pns);                       
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $i++);
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('G'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('H'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('I'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('J'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('K'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('L'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('M'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('N'.$rowCount, '');
    //         // $objPHPExcel->getActiveSheet()->SetCellValue('O'.$rowCount, '');
    //         // $rowCount++;
    //     }
    //     die();
    //     // $filename = "Diagnosa RJ ".date('d F Y', strtotime($param1))." - ".date('d F Y', strtotime($param2));
    //     $filename = "Daftar Nominatif PNS Rumkital Dr. Mintohardjo Periode Mei 2017";
    //     // $objPHPExcel->getActiveSheet()->SetCellValue('M'.$rowCount, "Total Pendapatan : ");
    //     // $objPHPExcel->getActiveSheet()->SetCellValue('N'.$rowCount, $total_pendapatan);
    //     header('Content-Disposition: attachment;filename="'.$filename.'.xls"');  
                
    //     // Rename worksheet (worksheet, not filename)  
    //     $objPHPExcel->getActiveSheet()->setTitle($namars);    
           
    //     // Redirect output to a client’s web browser (Excel2007)  
    //     //clean the output buffer  
    //     ob_end_clean();  
           
    //     //this is the header given from PHPExcel examples.   
    //     //but the output seems somewhat corrupted in some cases.  
    //     //header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
    //     //so, we use this header instead.  
    //     header('Content-type: application/vnd.ms-excel');  
    //     header('Cache-Control: max-age=0');  
           
    //     $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');  
    //     // $objWriter->save('php://output');  
    //     $this->SaveViaTempFile($objWriter);

    //     // $awal = $this->input->post('tanggal_awal');
    //     // $akhir = $this->input->post('tanggal_akhir');
    //     // $data_keuangan=$this->Labmlaporan->get_data_keu_tind($awal, $akhir)->result();
    //     // echo json_encode($data_keuangan);
    // }
                		
}
?>
