 <?php
defined('BASEPATH') OR exit('No direct script access allowed');
require_once(APPPATH.'controllers/Secure_area.php');
include(dirname(dirname(__FILE__)).'/Tglindo.php');
class Cuser extends Secure_area {
	public function __construct() {
		parent::__construct();
		$this->load->model('user/Muser','',TRUE);
		$this->load->model('ird/ModelKwitansi','',TRUE);
		
		$this->load->helper('url');
	}
	
	function index()
	{	   
		if($this->input->post('date0')!=''){
			$data['date_awal'] = $this->input->post('date0');
		}else {
			$data['date_awal'] = date('Y-m-d', strtotime('-1 days'));
		}
		
		if($this->input->post('date1')!=''){
			$data['date_akhir'] = $this->input->post('date1');
		}else {
			$data['date_akhir'] = date('Y-m-d');
		}		
		//	echo $data['date_awal'];echo $data['date_akhir'];
		$data['title'] = 'Daftar User Input IRD IRJ <b>'.date('d-m-Y', strtotime($data['date_awal'])).' s/d '.date('d-m-Y', strtotime($data['date_akhir'])).'</b>';
			
		$data['user_pasien']=$this->Muser->get_user_data_pasien($data['date_awal'],$data['date_akhir'])->result();
		$data['daful_ird']=$this->Muser->get_user_daful_ird($data['date_awal'],$data['date_akhir'])->result();
		$data['daful_irj']=$this->Muser->get_user_daful_irj($data['date_awal'],$data['date_akhir'])->result();
		$data['tind_ird']=$this->Muser->get_user_tind_ird($data['date_awal'],$data['date_akhir'])->result();
		$data['tind_irj']=$this->Muser->get_user_tind_irj($data['date_awal'],$data['date_akhir'])->result();
		$this->load->view('user/user_pasien',$data);			
		
	}

	public function all()
	{	   
		if($this->input->post('date0')!=''){
			$data['date_awal'] = $this->input->post('date0');
		}else {
			$data['date_awal'] = date('Y-m-d', strtotime('-1 days'));
		}
		
		if($this->input->post('date1')!=''){
			$data['date_akhir'] = $this->input->post('date1');
		}else {
			$data['date_akhir'] = date('Y-m-d');
		}		
		//2016-06-01 2016-07-18
		//	echo $data['date_awal'];echo $data['date_akhir'];
		$data['title'] = 'Daftar User Input Global <b>'.date('d-m-Y', strtotime($data['date_awal'])).' s/d '.date('d-m-Y', strtotime($data['date_akhir'])).'</b>';
			
		$data['user_all']=$this->Muser->get_user_all($data['date_awal'],$data['date_akhir'])->result();
		
		$this->load->view('user/user_all',$data);			
		
	}

	public function penunjang()
	{	   
		if($this->input->post('date0')!=''){
			$data['date_awal'] = $this->input->post('date0');
		}else {
			$data['date_awal'] = date('Y-m-d', strtotime('-1 days'));
		}
		
		if($this->input->post('date1')!=''){
			$data['date_akhir'] = $this->input->post('date1');
		}else {
			$data['date_akhir'] = date('Y-m-d');
		}		
		//	echo $data['date_awal'];echo $data['date_akhir'];
		$data['title'] = 'Daftar User Input Penunjang (Rad/Lab/Farmasi) <br>'.date('d-m-Y',strtotime($data['date_awal'])).' s/d '.date('d-m-Y',strtotime($data['date_akhir']));
			
		$data['rad']=$this->Muser->get_user_rad($data['date_awal'],$data['date_akhir'])->result();
		$data['cetak_rad']=$this->Muser->get_cetak_pl_rad($data['date_awal'],$data['date_akhir'])->result();
		$data['pa']=$this->Muser->get_user_pa($data['date_awal'],$data['date_akhir'])->result();
		$data['cetak_pa']=$this->Muser->get_cetak_pl_pa($data['date_awal'],$data['date_akhir'])->result();
		$data['lab']=$this->Muser->get_user_lab($data['date_awal'],$data['date_akhir'])->result();
		$data['cetak_lab']=$this->Muser->get_cetak_pl_lab($data['date_awal'],$data['date_akhir'])->result();
		$data['farmasi']=$this->Muser->get_user_farm($data['date_awal'],$data['date_akhir'])->result();
		$data['cetak_farm']=$this->Muser->get_cetak_pl_farm($data['date_awal'],$data['date_akhir'])->result();

		$this->load->view('user/user_penunjang',$data);			
		
	}

	public function cetak($tipe='', $tgl_awal='',$tgl_akhir='')
	{

		$tgl_indo=new Tglindo();
		

		date_default_timezone_set("Asia/Bangkok");
		$tgl_jam = date("d-m-Y H:i:s");
		//print_r($tampil);
		$data_rs=$this->ModelKwitansi->getdata_rs('10000')->result();
			$namars=$this->config->item('namars');
			$kota_kab=$this->config->item('kota');
			$alamat=$this->config->item('alamat');
			$nmsingkat=$this->config->item('namasingkat');
		////EXCEL 
		$this->load->library('Excel');  
		   
		// Create new PHPExcel object  
		$objPHPExcel = new PHPExcel();   
		   
		// Set document properties  
		$objPHPExcel->getProperties()->setCreator($namars)  
		        ->setLastModifiedBy($namars)  
		        ->setTitle("Laporan User ".$namars)  
		        ->setSubject("Laporan User ".$namars." Document")  
		        ->setDescription("Laporan User HMIS ".$namars." for Office 2007 XLSX, generated by HMIS.")  
		        ->setKeywords($namars)  
		        ->setCategory("Laporan User");  

		//$objReader = PHPExcel_IOFactory::createReader('Excel2007');    
		//$objPHPExcel = $objReader->load("project.xlsx");
		   
		$objReader= PHPExcel_IOFactory::createReader('Excel2007');
		$objReader->setReadDataOnly(true);
		$tgl1 = date('d F Y', strtotime($tgl_awal));	
		$tgl2 = date('d F Y', strtotime($tgl_akhir));

		if($tipe=='new'){				
			$data_user=$this->Muser->get_user_data_pasien($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='all'){
			$data_user=$this->Muser->get_user_all($tgl_awal,$tgl_akhir)->result();
			$tgl1=''; $tgl2='';
		}
		else if($tipe=='dird'){
			$data_user=$this->Muser->get_user_daful_ird($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='dirj'){
			$data_user=$this->Muser->get_user_daful_irj($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='tird'){
			$data_user=$this->Muser->get_user_tind_ird($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='tirj'){
			$data_user=$this->Muser->get_user_tind_irj($tgl_awal,$tgl_akhir)->result();
		}
		
		$objPHPExcel=$objReader->load(APPPATH.'third_party/lap_user_new_patient_tgl.xlsx');
				// Set active sheet index to the first sheet, so Excel opens this as the first sheet  
				$objPHPExcel->setActiveSheetIndex(0);  
				// Add some data  
				$objPHPExcel->getActiveSheet()->SetCellValue('A1', $data['title']);
				$objPHPExcel->getActiveSheet()->SetCellValue('A2', 'Tanggal : '.$tgl1.' - '.$tgl2);

				$vtot1=0;$vtot2=0;
				$i=1;
				$rowCount = 5;
				//print_r($data_user); break;
				foreach($data_user as $row){				
					$j=1;		
					$vtot1=$vtot1+$row->total;
					 
								$objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $i);
								$objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->total);
								$objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $row->xuser);
							 	$i++;
							 								
						$rowCount++;
						// if
					
				}
				
				$objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, 'Total Input');
				$objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount,  $vtot1);
				$objPHPExcel->getActiveSheet()->getStyle('B'.$rowCount)->applyFromArray(
				    array(
					'fill' => array(
					    'type' => PHPExcel_Style_Fill::FILL_SOLID,
					    'color' => array('rgb' => 'C1B2B2')
					)
				    )
				);
				
				header('Content-Disposition: attachment;filename="Lap_'.$tipe.'_TGL_'.date('d-m-Y', strtotime($tgl_awal)).'_'.date('d-m-Y', strtotime($tgl_akhir)).'.xlsx"');  

		// Rename worksheet (worksheet, not filename)  
		$objPHPExcel->getActiveSheet()->setTitle($namars);  
		   
		   
		   
		// Redirect output to a client’s web browser (Excel2007)  
		//clean the output buffer  
		ob_end_clean();  
		   
		//this is the header given from PHPExcel examples.   
		//but the output seems somewhat corrupted in some cases.  
		//header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
		//so, we use this header instead.  
		header('Content-type: application/vnd.ms-excel');  
		header('Cache-Control: max-age=0');  
		   
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');  
		$objWriter->save('php://output');  					
	}

	//////////////////////////////////////////////////////////////////////////////////////
	public function cetak_penunjang($tipe='', $tgl_awal='',$tgl_akhir='')
	{

		$tgl_indo=new Tglindo();
		

		date_default_timezone_set("Asia/Bangkok");
		$tgl_jam = date("d-m-Y H:i:s");
		//print_r($tampil);
		$namars=$this->config->item('namars');
			$kota_kab=$this->config->item('kota');
			$alamat=$this->config->item('alamat');
			$nmsingkat=$this->config->item('namasingkat');
		////EXCEL 
		//$this->load->library('Excel');  
		$this->load->file(APPPATH.'third_party/PHPExcel.php');    
		// Create new PHPExcel object  
		$objPHPExcel = new PHPExcel();   
		   
		// Set document properties  
		$objPHPExcel->getProperties()->setCreator($namars)  
		        ->setLastModifiedBy($namars)  
		        ->setTitle("Laporan User ".$namars)  
		        ->setSubject("Laporan User ".$namars." Document")  
		        ->setDescription("Laporan User HMIS ".$namars." for Office 2007 XLSX, generated by HMIS.")  
		        ->setKeywords($namars)  
		        ->setCategory("Laporan User");  

		//$objReader = PHPExcel_IOFactory::createReader('Excel2007');    
		//$objPHPExcel = $objReader->load("project.xlsx");
		   
		$objReader= PHPExcel_IOFactory::createReader('Excel2007');
		$objReader->setReadDataOnly(true);
		$tgl1 = date('d F Y', strtotime($tgl_awal));	
		$tgl2 = date('d F Y', strtotime($tgl_akhir));

		if($tipe=='rad'){				
			$data_user=$this->Muser->get_user_rad($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='lab'){
			$data_user=$this->Muser->get_user_lab($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='pa'){
			$data_user=$this->Muser->get_user_pa($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='farm'){
			$data_user=$this->Muser->get_user_farm($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='krad'){
			$data_user=$this->Muser->get_cetak_pl_rad($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='kpa'){
			$data_user=$this->Muser->get_cetak_pl_pa($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='klab'){
			$data_user=$this->Muser->get_cetak_pl_lab($tgl_awal,$tgl_akhir)->result();
		}
		else if($tipe=='kfarm'){
			$data_user=$this->Muser->get_cetak_pl_farm($tgl_awal,$tgl_akhir)->result();
		}
		
		$objPHPExcel=$objReader->load(APPPATH.'third_party/lap_user_new_patient_tgl.xlsx');
				// Set active sheet index to the first sheet, so Excel opens this as the first sheet  
				$objPHPExcel->setActiveSheetIndex(0);  
				// Add some data  
				$objPHPExcel->getActiveSheet()->SetCellValue('A1', $data['title']);
				$objPHPExcel->getActiveSheet()->SetCellValue('A2', 'Tanggal : '.$tgl1.' - '.$tgl2);

				$vtot1=0;$vtot2=0;
				$i=1;
				$rowCount = 5;

				//print_r($data_user); break;
				foreach($data_user as $row){		
					$vtot1=$vtot1+$row->total;
					$j=1;		
					if($tipe=='lab' || $tipe=='rad' || $tipe=='farm'){
						$xuser = $row->xinput;
					}else
					 	$xuser = $row->xuser;
								$objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $i);
								$objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $row->total);
								$objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $xuser);
							 	$i++;
							 								
						$rowCount++;
						// if
					
				}
				
				$objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, 'Total Input');
				$objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount,  $vtot1);
				$objPHPExcel->getActiveSheet()->getStyle('B'.$rowCount)->applyFromArray(
				    array(
					'fill' => array(
					    'type' => PHPExcel_Style_Fill::FILL_SOLID,
					    'color' => array('rgb' => 'C1B2B2')
					)
				    )
				);
				
				header('Content-Disposition: attachment;filename="Lap_'.$tipe.'_TGL_'.date('d-m-Y', strtotime($tgl_awal)).'_'.date('d-m-Y', strtotime($tgl_akhir)).'.xlsx"');  

		// Rename worksheet (worksheet, not filename)  
		$objPHPExcel->getActiveSheet()->setTitle($namars);  
		   
		   
		   
		// Redirect output to a client’s web browser (Excel2007)  
		//clean the output buffer  
		ob_end_clean();  
		   
		//this is the header given from PHPExcel examples.   
		//but the output seems somewhat corrupted in some cases.  
		//header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');  
		//so, we use this header instead.  
		header('Content-type: application/vnd.ms-excel');  
		header('Cache-Control: max-age=0');  
		   
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');  
		$objWriter->save('php://output');  					
	}
}

?>
